### ISSUE TITLE
edit URL

### ISSUE THREAD

**Issue by rami-nasfi** [edgafner/GBrowser#124]
Hello , 
i see after resizing the window (make it smaller) ,i cant edit the url , just make it bigger again , then write my url , then resize it again to make  the window smaller , can you check this 

small window **i can't** select url:
![Screen Shot 2023-10-09 at 11 53 37 AM](https://github.com/edgafner/GBrowser/assets/115596797/34c774c7-1915-4fb2-b632-3a9981336d4e)

big window **i can** select url:
![Screen Shot 2023-10-09 at 11 54 18 AM](https://github.com/edgafner/GBrowser/assets/115596797/08280953-b50c-49d5-84c6-17e4a519ad74)

**Comment by Jonatha1983** [comment]
Hi @rami-nasfi 

This was fixed in the upcoming release (v2024.1.3) 

Thanks for reporting.
