### ISSUE TITLE
[FEATURE]: Copy link address ➕ open in browser

### ISSUE THREAD

**Issue by magicprinc** [edgafner/GBrowser#147]
There is no easy way to copy a link from the page opened in GBrowser
and/or open this link in a (default) browser.

1) Could you please add action into the popup-menu: Copy link address
(as in Chrome)

2) Could you please add action into the popup-menu: Open in Browser
Optional: can live without it if 1^ is implemented :-)

**Comment by Jonatha1983** [comment]
@magicprinc I am not sure I got your request, but there are many new features in the upcoming release of v2024.1.3. (will be public available in the upcoming days) 

Please check the new version and let me know if it fulfills your request. 

Thanks
