### ISSUE TITLE
[ui] url shown only as popup window and the toolbar is too high

### ISSUE THREAD

**Issue by wizzard0** [edgafner/GBrowser#20]
1) compared to other embedded browser plugins and sidebars, toolbar is high (like 1.6x higher) and takes too much screen space

2) what's the reason of making URL visible as popup window only? weird

Attached screenshot for clarity

![image](https://user-images.githubusercontent.com/424619/134799759-9e609101-5669-4c30-9456-a8931e9cb173.png)

**Comment by Jonatha1983** [comment]
@wizzard0 About point 2: 
It is not only visible as a pop up - you need to increase the width of the toolwindow - Jetbrains recommend not to set a default width size to toolwindow so not sure how to make it better 

About 1.  this is the default size of the height of a toolbar in the IDE, I did not change the height of it so not sure what other embedded browser are doing - any examples ?

**Comment by Jonatha1983** [comment]
@wizzard0  I resized the input text should take less screen space. 
You can check the new version in [here](https://plugins.jetbrains.com/plugin/22319-azd/edit/versions)
Closing this issue for now.
