### ISSUE TITLE
Google Chrome Authentication

### ISSUE THREAD

**Issue by Jonatha1983** [edgafner/GBrowser#35]
Chrome changed the way CEFBrowser authentication are working and users cannot log in in their account.

**Comment by bengabp** [comment]
When i try to login from google , im presented with this error page
![image](https://github.com/edgafner/GIdeaBrowser/assets/84660669/5c1aeea1-c739-4884-8c66-1ddfaa659af4)

**Comment by Jonatha1983** [comment]
Yes @bengabp  this is a known issue - and hard to overcome

More details in [here](https://magpcss.org/ceforum/viewtopic.php?t=16717)

**Comment by Jonatha1983** [comment]
@bengabp this is now fixed in the upcoming version v2024.1.3 

thanks for reporting.

**Comment by v1bh0r** [comment]
I have the version 2024.3.4 installed and faced the same issue.
<img width="505" alt="Screenshot 2024-11-28 at 6 28 19 AM" src="https://github.com/user-attachments/assets/bc41a074-f087-468d-aab9-583c01554ac1">
