### ISSUE TITLE
GIdeaBrowser, when docked and then clicked, locks out typing text or clicking on CLion menus

### ISSUE THREAD

**Issue by DavidAntliff** [edgafner/GBrowser#54]
Using GIdeaBrowser 1.0.27 in CLion 2022.3.1 (classic UI), on Ubuntu 22.04, i3wm 4.22.

When the browser panel is open, and I click anywhere on it with the mouse, I am then _unable to type any text into other source windows, or CLion-hosted terminals, debug panels, or click any CLion menus_. The icons on the toolbar still work though.

To get back control, I need to "minimise" GIdeaBrowser back to the right-hand side gutter, or detach the window and make it float. If I make it float, and then redock it to the main CLion window, I can continue to type and click menu items _until I click the GIdeaBrowser window again_, at which point my ability to type and click menus is again disabled.

Unfortunately, in this state, it's mostly unusable, as I need to interact with the GIdeaBrowser window frequently.

**Comment by Jonatha1983** [comment]
Hi @DavidAntliff 

Will try to reproduce it and let you know. 

Thanks.

**Comment by DavidAntliff** [comment]
Thanks. Not sure if it’s relevant, but I also have mouse focus enabled (window focus follows mouse pointer).

**Comment by Jonatha1983** [comment]
@DavidAntliff, a new version with many new features, v2024.1.3, will be available in the coming days. 

I just wanted to let you know I'm closing this issue for now. 

Thanks for reporting.
