### ISSUE TITLE
Open as Editor Tab, with dev-tools

### ISSUE THREAD

**Issue by judison** [edgafner/GBrowser#75]

**Comment by Jonatha1983** [comment]
Hi 
Please provide more details - is it a question? is it a feature request? thanks

**Comment by judison** [comment]
It's a Feature Request.

I think it would be great for GIB to open as an Editor tab... (N editor tabs actually, like browser tabs) 
and dev-tools inside that tab, or as a tool window

**Comment by Jonatha1983** [comment]
@judison this feature is now available in the upcoming release v2024.1.3

Thanks for reporting.
